name: external_path_ios_mac
description: "A Flutter package for restoring directory paths on iOS and macOS devices, ensuring file access and management across platforms."
version: 0.0.2
homepage: "https://github.com/SwanFlutter/external_path_ios_mac"

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  plugin:
    platforms:
      ios:
        pluginClass: ExternalPathIosMacPlugin
      macos:
        pluginClass: ExternalPathIosMacPlugin



